# Generated by Django 5.1.7 on 2025-05-03 03:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('qrcode', 'QRcode')], default='cash', max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Peding'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='orders.order')),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
    ]
