# Generated by Django 5.1.7 on 2025-05-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
