# Generated by Django 5.1.7 on 2025-05-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0003_alter_orderdetail_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product_name',
            new_name='product_name_snap',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product_price',
            new_name='product_price_snap',
        ),
    ]
