# Generated by Django 5.1.7 on 2025-05-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0004_rename_product_name_orderdetail_product_name_snap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product_name_snap',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product_price_snap',
            new_name='product_price',
        ),
    ]
