# Generated by Django 5.1.7 on 2025-05-13 02:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_image', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_image', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('discount', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
    ]
